# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordertime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
